[package]
name = "watchman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
notify-rust = "4.8.0"
psutil = "3.2.2"
sysinfo = "0.29.8"
